molecule :
    file : restraints/2kid.seq
    type : nv

angles : 
    - file : restraints/dih.tbl
      type : xplor

distances :
    - 
      file : restraints/dis.tbl
      type : xplor
    -  
      file : restaints/hydcon.tbl
      type : xplor

anneal:
    steps : 15000
    highTemp : 5000.0
    irpWeight : 0.0
    swap : 20
