molecule :
    file : restraints/2lu0.seq
    ptype : rna
    type : nv

rna : 
    ribose : Constrain

distances :
    - file : restraints/distances
      type : cyana

angles :
    - file : restraints/dihedrals.aco
      type : cyana

anneal:
    steps : 15000
    highTemp : 5000.0
    swap : 20
