molecule :
    file : input/2lu0.seq
    ptype : rna
    type : nv
    chain : 'A'

rna : 
    ribose : Constrain

angles : 
    - file : input/dih.tbl
      type : xplor

distances :
    - file : input/dis.tbl
      type : xplor

anneal:
    dynOptions :
        steps : 15000
        highTemp : 5000.0
    param :
        swap : 20

