molecule :
   -
    file : 2m57.seq
    ptype : rna
    type : nv

rna : 
    ribose : Constrain

angles : 
    - file : odih.mr
      type : xplor

distances :
    - file : dis.tbl
      file : hydcon.tbl
      type : xplor

anneal:
    steps : 15000
    highTemp : 5000.0
    irpWeight : 0.0
