molecule :
    file : restraints/2kid.seq
    type : nv

distances :
    - file : restraints/distances
      type : cyana

angles :
    - file : restraints/dihedrals.aco
      type : cyana

anneal:
    steps : 15000
    highTemp : 5000.0
    irpWeight : 0.0
    swap : 20
