molecule :
    file : 3gb1.seq
    type : nv

distances :
    - file : distances
      type : cyana

angles :
    - file : dihedrals.aco
      type : cyana

anneal:
    steps : 15000
    highTemp : 5000.0
    swap : 20
