molecule :
   -
    file : 2m57.seq
    ptype : rna
    type : nv

rna :
    ribose : Constrain

distances :
    - file : distances
      type : cyana

angles :
    - file : odih.mr
      type : xplor

anneal:
    steps : 15000
    highTemp : 5000.0
    irpWeight : 0.0
