molecule :
    file : input/1d3z.seq
    type : nv
    chain : 'A'

angles : 
    - file : input/dih.tbl
      type : xplor

distances :
    - 
      file : input/dis.tbl
      type : xplor
    - 
      file : input/hydcon.tbl
      type : xplor

anneal:
    dynOptions :
        steps : 15000
        highTemp : 5000.0
    param :
        swap : 20

