molecule :
    file : input/2m24.seq
    ptype : rna
    type : nv

rna : 
    ribose : Constrain

distances :
    - file : input/distances
      type : cyana

angles :
    - file : input/dihedrals.aco
      type : cyana

anneal:
    steps : 15000
    highTemp : 5000.0
    irpWeight : 0.0
    swap : 20
