molecule :
   -
    file : 2koc.seq
    ptype : rna
    type : nv

rna : 
    ribose : Constrain

angles : 
    - file : dih.tbl
      type : xplor

distances :
    - file : dis1.tbl
      type : xplor
    - file : dis2.tbl
      type : xplor
    - file : hydcon.tbl
      type : xplor

anneal:
    steps : 15000
    highTemp : 5000.0
    irpWeight : 0.0
    swap : 20
