molecule :
    file : input/2ezx.seq
    type : nv

distances :
    - file : input/distances
      type : cyana

angles :
    - file : input/dihedrals.aco
      type : cyana

anneal:
    steps : 15000
    highTemp : 5000.0
    swap : 20
