molecule :
    file : input/2kid.seq
    type : nv

angles : 
    - file : input/angle.mr
      type : xplor

distances :
#    - 
#      file : input/distance.mr
#      type : xplor
#    - 
#      file : input/dis1.tbl
#      type : xplor
    - 
      file : input/noeambi_distance.mr
      type : xplor
    -  
      file : input/hyd.mr
      type : xplor

anneal:
    dynOptions :
        steps : 15000
        highTemp : 5000.0
    param :
        swap : 20

