molecule :
    file : input/2l5z.seq
    ptype : rna
    type : nv
    chain : 'A'

rna : 
    ribose : Constrain

distances :
    - 
      file : input/dis1.tbl
      type : xplor
    - 
      file : input/dis2.tbl
      type : xplor
    - 
      file : input/dis3.tbl
      type : xplor
    - 
      file : input/hydcon.tbl
      type : xplor

angles :
    - file : input/dih.tbl
      type : xplor

anneal:
    dynOptions :
        steps : 15000
        highTemp : 5000.0
    param :
        swap : 20

